### ISSUE TITLE
Affinity recipes not finding a match

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/peterkelm-recipes#7]
Hi, 

It looks like the Affinity recipes (I've personally tested the Affinity Designer and Affinity Publisher ones) are failing to find a match on the download page.

```The following recipes failed:
    com.github.peterkelm.download.AffinityDesigner
        Error in com.github.peterkelm.download.AffinityDesigner: Processor: URLTextSearcher: Error: No match found on URL: https://store.serif.com/de/update/macos/designer/1/

Nothing downloaded, packaged or imported.
```

I'm gonna see if this is something that I can fix and raise a PR for

**Comment by Daz-wallace** [comment]
Hmm ok, so it looks like it's a Serif thing 🙄
https://affinity.serif.com
![Screenshot 2022-11-09 at 08 37 02](https://user-images.githubusercontent.com/4480783/200780703-acc324a5-8e83-422c-9a56-12fedc6215dd.png)

**Comment by peterkelm** [comment]
@Daz-wallace, indeed the issue currently is that the Affinity store is down...

Anyhow, I'll have an eye on this going forward.
